export const TOKENS = {
  Database: Symbol('Database'),

  CustomerTokenVerifier: Symbol('CustomerTokenVerifier'),
  RestaurantTokenVerifier: Symbol('RestaurantTokenVerifier'),
  CustomerAuthGateway: Symbol('CustomerAuthGateway'),
  RestaurantAuthGateway: Symbol('RestaurantAuthGateway'),
  StorageGateway: Symbol('StorageGateway'),
  ImageProcessor: Symbol('ImageProcessor'),
  MediaBaseUrl: Symbol('MediaBaseUrl'),

  CustomersRepository: Symbol('CustomersRepository'),
  RestaurantUsersRepository: Symbol('RestaurantUsersRepository'),
  MembershipsRepository: Symbol('MembershipsRepository'),
  RestaurantsRepository: Symbol('RestaurantsRepository'),
  OpeningHoursRepository: Symbol('OpeningHoursRepository'),
  CuisinesRepository: Symbol('CuisinesRepository'),
  MenuCategoriesRepository: Symbol('MenuCategoriesRepository'),

  SignUpCustomerUseCase: Symbol('SignUpCustomerUseCase'),
  SignInCustomerUseCase: Symbol('SignInCustomerUseCase'),
  RefreshCustomerSessionUseCase: Symbol('RefreshCustomerSessionUseCase'),
  RefreshRestaurantSessionUseCase: Symbol('RefreshRestaurantSessionUseCase'),
  SignUpRestaurantUserUseCase: Symbol('SignUpRestaurantUserUseCase'),
  SignInRestaurantUserUseCase: Symbol('SignInRestaurantUserUseCase'),
  CreateMemberUseCase: Symbol('CreateMemberUseCase'),
  ListMyRestaurantsUseCase: Symbol('ListMyRestaurantsUseCase'),
  CreateRestaurantUseCase: Symbol('CreateRestaurantUseCase'),
  GetRestaurantUseCase: Symbol('GetRestaurantUseCase'),
  UpdateRestaurantUseCase: Symbol('UpdateRestaurantUseCase'),
  ActivateRestaurantUseCase: Symbol('ActivateRestaurantUseCase'),
  SetAcceptingOrdersUseCase: Symbol('SetAcceptingOrdersUseCase'),
  ListOpeningHoursUseCase: Symbol('ListOpeningHoursUseCase'),
  ReplaceOpeningHoursUseCase: Symbol('ReplaceOpeningHoursUseCase'),
  ListCuisineCategoriesUseCase: Symbol('ListCuisineCategoriesUseCase'),
  ListRestaurantCuisinesUseCase: Symbol('ListRestaurantCuisinesUseCase'),
  ReplaceRestaurantCuisinesUseCase: Symbol('ReplaceRestaurantCuisinesUseCase'),
  ListMenuCategoriesUseCase: Symbol('ListMenuCategoriesUseCase'),
  CreateMenuCategoryUseCase: Symbol('CreateMenuCategoryUseCase'),
  UpdateMenuCategoryUseCase: Symbol('UpdateMenuCategoryUseCase'),
  ArchiveMenuCategoryUseCase: Symbol('ArchiveMenuCategoryUseCase'),
  ReorderMenuCategoriesUseCase: Symbol('ReorderMenuCategoriesUseCase'),
  CreateImageUploadUseCase: Symbol('CreateImageUploadUseCase'),
  ProcessImageVariantsUseCase: Symbol('ProcessImageVariantsUseCase')
} as const
